import LegalPage from '../components/LegalPage'

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="June 2026"
      intro="These Terms govern your use of Strykd. By creating an account or using the service, you agree to them. If you do not agree, please do not use Strykd."
      sections={[
        { title: 'The service', body: [
          'Strykd is an AI-powered accountability and planning tool. It turns your goals into daily plans, gives you a shareable progress page, and lets you create collaborative shared lists. Features may change over time as we improve the product.',
        ]},
        { title: 'Your account', body: [
          'You are responsible for keeping your login credentials secure and for all activity under your account. Provide accurate information and keep it up to date. You must be at least 13 years old to use Strykd.',
        ]},
        { title: 'Free trial, subscription, and billing', body: [
          'New users get a 30-day free trial with full access and no card required. After the trial, continued access to the dashboard and AI features requires a subscription of $9 per month, billed through Stripe.',
          'Your subscription renews automatically each month until you cancel. You can cancel anytime from Settings; access continues until the end of the current billing period.',
          'Refunds: you may request a full refund of your most recent payment within 7 days of subscribing, from Settings. A refund cancels your subscription immediately.',
        ]},
        { title: 'Your content', body: [
          'You own the content you create on Strykd (goals, tasks, notes, photos, lists). You grant us the limited license needed to host, display, and process it to provide the service, including generating AI plans and itineraries and showing your public page when you choose to make it public.',
          'You are responsible for the content you post. Do not upload content that is illegal, infringing, or that you do not have the right to share.',
        ]},
        { title: 'Public pages and shared lists', body: [
          'Public pages and shared lists are visible to anyone with the link. Anyone with a shared-list link can view and edit that list without an account. Do not include sensitive or confidential information in anything you make public.',
        ]},
        { title: 'Acceptable use', body: [
          'Do not misuse the service: no attempts to break, overload, or reverse engineer it; no scraping; no using it to harass others or to send spam; no unlawful activity. We may suspend or terminate accounts that violate these Terms.',
        ]},
        { title: 'AI-generated content', body: [
          'Plans, suggestions, reviews of proof, and itineraries are generated by AI and provided for guidance only. They may be inaccurate or incomplete. Use your own judgment, especially for health, financial, legal, or other important decisions. Strykd is not a substitute for professional advice.',
        ]},
        { title: 'Disclaimers and liability', body: [
          'Strykd is provided "as is" without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that it will help you achieve any particular outcome. To the maximum extent permitted by law, Strykd is not liable for any indirect, incidental, or consequential damages, and our total liability is limited to the amount you paid us in the 12 months before the claim.',
        ]},
        { title: 'Termination', body: [
          'You can stop using Strykd and delete your account at any time from Settings. We may suspend or end your access if you violate these Terms or if we discontinue the service.',
        ]},
        { title: 'Changes and contact', body: [
          'We may update these Terms; material changes will be reflected by the date above, and continued use means you accept the updated Terms. Questions? Email hello@strykdapp.com.',
        ]},
      ]}
    />
  )
}
